### ISSUE TITLE
[Idea] Use Collections instead of default arrays

### ISSUE THREAD

**Issue by NoelDavies** [endclothing/prometheus_client_php#5]
I know that it requires another dependency, but what is people's thoughts on using Collections over vanilla arrays for a lot of what's being used currently.

I personally think it would make things a lot cleaner and easier to read, use and understand.

**Comment by bvisness** [comment]
If you're referring to https://www.php.net/manual/en/class.ds-collection.php, then that would require everybody to install the ds extension, which would definitely be a breaking change. It would be wiser to stick with vanilla arrays so more people can actually use this library.

**Comment by NoelDavies** [comment]
I was referring to the tightenco/collection library - https://github.com/tightenco/collect
