### ISSUE TITLE
Ability to inject Redis client in redis storage

### ISSUE THREAD

**Issue by martinssipenko** [endclothing/prometheus_client_php#7]
Rigth now `\Redis` client is constructed within `__construct` method of `Prometheus\Storage\Redis` class. What thoughts do you have on adding ability to inject `\Redis ` into storage class? This would allow to reuse already existing connection from framework.

I'm happy to contribute the code change if/when it's decided to do it and what would be the best approach to do it.

**Comment by NoelDavies** [comment]
I'm down for that if others are open to it - the only thing is it's a huge method signature change and would not be backwards compat. So we'd have to solve this in one of the following ways (open to others, these are just the ideas I can see):

 - Create a public static factory (named constructor) for this, and have that constructed through that
 - Bump the version (don't like this idea)
 - Create a standalone factory with the same original signature and pass the existing client as an optional argument.

**Comment by martinssipenko** [comment]
I personally like the names constructor option. Let me try it out and I'll send some code your way when I have something to show.

**Comment by martinssipenko** [comment]
Just noticed that `$this->openConnection();` is being called in all methods. This would gave to change in case Redis is injected as the connection would have been established already.

I see two options here:
- Move the call to `__construct`.
- Add an if statement in `openConnection` method that would check against private property, if it's set `openConnection` would exit early.

WDYT?

**Comment by martinssipenko** [comment]
Here is a draft PR: https://github.com/endclothing/prometheus_client_php/pull/8

**Comment by NoelDavies** [comment]
The existing connection would still have to be injected, but nice find!

**Comment by martinssipenko** [comment]
Closed by #8
